Vagrant.configure("2") do |config|
  # Para usar un archivo .box local descomenta la siguiente línea y especifica la ruta:
  # config.vm.box_url = "file://./ubuntu-bionic.box"
  
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "so-environment"
  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm-sistemas-operativos"
    vb.memory = "2048"
    vb.cpus = 2
    vb.gui = true
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Aprovisionamiento con el script compartido
  config.vm.provision "shell", path: "scripts/setup_env.sh"
end
